### ISSUE TITLE
[Bug]: Incompatible with Snow Day

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/leavesbegone#1]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0

### Notes (Required)

1. Install Leaves Be Gone and [Snow Day](https://www.curseforge.com/minecraft/mc-mods/snowday)
2. Grow/find a tree, break all its logs
3. Observe, that leaves are not decaying any faster, than vanilla

I checked out a similar mod, [SnowyLeavesPlus](https://www.curseforge.com/minecraft/mc-mods/snowyleavesplus), and it doesn't have the same issue, so let me know if this needs to be fixed on Snow Day's end.

### latest.log (Optional)

https://gist.github.com/SplendidAlakey/03548dd76dc6f482a0cde8d39da21792

**Comment by Fuzss** [comment]
That's caused by this: https://github.com/mineblock11/Snowday/blob/f67d0a62380845ce6668427313032a09f8f2592d/src/main/java/mine/block/snowday/mixins/LeavesBlockMixin.java#L46

Snow Day makes leaves blocks constantly random tick, while in vanilla they only start to random tick when they can decay. Leaves Be Gone uses that change in being able to random tick to apply its logic.

**Comment by Fuzss** [comment]
I'm a little confused though why SnowyLeavesPlus would work, Snow Day just copies that part of it, there is no difference...

I'll look into this.

**Comment by Fuzss** [comment]
Alright, so SnowyLeavesPlus has a tiny bug right now effectively breaking the whole mod, therefore it's allowing Leaves Be Gone to still function. When the bug is fixed though the behavior will be the same as with the Snow Day mod.

I'm not sure yet how I want to go about this, as the whole purpose of Leaves Be Gone is to be as efficient as possible, and compatibility with those two mods would certainly require a different approach to the logic of Leaves Be Gone making it less efficient...

**Comment by SplendidAlakey** [comment]
Thanks for the replies and making the report to SnowyLeavesPlus.

And, if nothing else, marking mods as incompatible in fabric.mod.json would be a good compromise, as right now there's no way to know that Leaves Be Gone doesn't function at all, when either of these mods is present, unless you binary search. Since your mod focuses on efficiency and there are plenty of other mods, that introduce fast leaves decay, I would say it's not worth sacrificing efficiency for compatibility with a very small amount of mods. I tested the rest of my modpack and Snow Day was the only conflicting mod.

**Comment by Fuzss** [comment]
Yeah, that's probably the best approach to this issue. Thanks!
